language: python
sudo: false

cache:
  pip: true
  directories:
    - here

services:
  - docker

env:
  global:
    - |
      RDB_TAG="latest"
      LUA="lua 5.3"
      LUA_PATH="lua53"
  matrix:
     - |
       LUA="lua 5.1"
       LUA_PATH="lua51"
     - |
       LUA="lua 5.2"
       LUA_PATH="lua52"
     - |
       LUA="luajit 2.0"
       LUA_PATH="jit20"
     - |
       LUA="luajit 2.1"
       LUA_PATH="jit21"
     - RDB_TAG="2.3.1"
     - RDB_TAG="2.2.6"
     - RDB_TAG="2.0.4"

before_install:
  - pip install hererocks
  - hererocks here/$LUA_PATH -r^ --$LUA
  - source here/$LUA_PATH/bin/activate
  - luarocks install luacheck
  - luacheck .
  # Fix from https://github.com/leafo/lapis/issues/6
  - luarocks install https://gist.githubusercontent.com/starius/b20d3e63929ae678c857/raw/4b4499f442337b6f577422364358590bd00c9d48/luacrypto-0.3.2-2.rockspec

install:
  - luarocks build --only-deps lua-reql-1.0.4-0.rockspec
  - luarocks build reql-1.0.4-0.rockspec

before_script:
  - docker pull rethinkdb:$RDB_TAG
  - docker run -d -p 28015:28015 rethinkdb
  - luarocks install busted
  - luarocks install luacov-coveralls

script:
  - busted --exclude-tags="expensive"

before_cache:
  - rm -rf $HOME/.cache/pip/log

after_success:
  - luacov-coveralls
